const exifIndexMap = [
  "Artist",
  "Model",
  "DateTime",
  "ExifVersion",
  "ExposureTime",
  "FNumber",
  "Make",
  "MaxApertureValue",
  "MeteringMode",
  "DateTimeOriginal",
  "DateTimeDigitized",
  "ColorSpace",
  "ExposureMode",
  "ExposureProgram",
  "ComponentsConfiguration",
  "Flash",
  "GPSLatitude",
  "GPSLongitude",
  "GPSAltitude",
  "ISOSpeedRatings",
  "ShutterSpeedValue",
  "BrightnessValue",
  "FocalLength",
  "ResolutionUnit",
  "WhiteBalance",
  "XResolution",
  "YResolution",
  "GPSProcessingMethod",
  "GPSDateStamp",
  "GPSDateStamp",
  "GPSImgDirection",
  "GPSImgDirectionRef",
  "GPSLatitude",
  "GPSLongitude",
  "GPSAltitude",
  "GPSProcessingMethod",
  "GPSDateStamp",
];
const reverseExifMap = {
  Artist: 0,
  Model: 1,
  DateTime: 2,
  ExifVersion: 3,
  ExposureTime: 4,
  FNumber: 5,
  Make: 6,
  MaxApertureValue: 7,
  MeteringMode: 8,
  DateTimeOriginal: 9,
  DateTimeDigitized: 10,
  ColorSpace: 11,
  ExposureMode: 12,
  ExposureProgram: 13,
  ComponentsConfiguration: 14,
  Flash: 15,
  GPSLatitude: 16,
  GPSLongitude: 17,
  GPSAltitude: 18,
  ISOSpeedRatings: 19,
  ShutterSpeedValue: 20,
  BrightnessValue: 21,
  FocalLength: 22,
  ResolutionUnit: 23,
  WhiteBalance: 24,
  XResolution: 25,
  YResolution: 26,
  GPSProcessingMethod: 27,
  GPSDateStamp: 29,
  GPSImgDirection: 30,
  GPSImgDirectionRef: 31,
};

export { exifIndexMap, reverseExifMap };
